export const forbiddenWords = [
    "abusif",
    "argent",
    "arrogant",
    "bête",
    "bouffon",
    "casse-couilles",
    "con",
    "connard",
    "crétin",
    "détestable",
    "débile",
    "enfoiré",
    "idiot",
    "imbécile",
    "incompétent",
    "insulte",
    "merde",
    "mauvais",
    "nazi",
    "pute",
    "raciste",
    "salopard",
    "sale",
    "vulgaire",
    "abuse",
    "asshole",
    "bastard",
    "bitch",
    "bloody",
    "bullshit",
    "cunt",
    "dick",
    "douchebag",
    "fuck",
    "goddamn",
    "hell",
    "idiot",
    "motherfucker",
    "nigga",
    "prick",
    "pussy",
    "retard",
    "shit",
    "slut",
    "twat",
    "vagina",
    "whore",
    "sôkôlô",
    "fanjakana",
    "ratsy",
    "bevohoka",
    "vovoka",
    "tsimoka",
    "ambodivava",
    "dahalo",
    "mpisasy",
    "mijaly",
    "harerahana",
    "fanina",
    "hatahorana",
    "mampiady",
    "maloto",
    "vato",
    "lahy",
    "mba",
    "azoko",
    "babo",
    "mpiaro",
    "mampitady",
    "fory",
    "lely",
    "dondrona",
    "lataka",
    "vody",
    "vendrana",
    "adala",
    "pory",
    "kindy",
    "kimason",
    "vendram",
    "connard",
    "connasse",
    "pute",
    "salope",
    "enculé",
    "salope",
    "casse-couilles",
    "fils de pute",
    "merde",
    "putain",
    "trou du cul",
    "vieux con",
    "baltringue",
    "bâtard",
    "bouffon",
    "caca",
    "cagué",
    "cul",
    "déconner",
    "gros con",
    "merdeux",
    "nase",
    "niquer",
    "pédé",
    "pouffiasse",
    "raclure",
    "salopard",
    "tapette",
    "tarlouze",
    "taré",
    "tête de con",
    "viande de bête",
    "zgeg",
    "kéké",
    "débile",
    "idiot",
    "bête",
    "abruti",
    "crétin",
    "andouille",
    "boulet",
    "morveux",
    "niais",
    "poulet",
    "schizo",
    "squelette",
    "vieux débris",
    "zéro",
    "débile mental",
    "mémé",
    "débile",
    "foutoir",
    "gaulois",
    "indigène",
    "raclure",
    "schizo",
    "squelette",
    "taré",
    "vieux débris",
    "vieux con",
    "débile mental",
    "foutre",
    "gland",
    "gros c**",
    "pignouf",
    "putois",
    "puceau",
    "raclure de bidet",
    "raclure de fond de tiroir",
    "singe",
    "souris",
    "tête de gland",
    "tête de mule",
    "tête de pioche",
    "tête de turc",
    "vieux con",
    "motherfucker",
    "nigga",
    "nigger",
    "piss",
    "prick",
    "pussy",
    "shit",
    "slut",
    "son of a bitch",
    "twat",
    "wanker",
    "whore",
    "bastard",
    "cocksucker",
    "cum",
    "dickhead",
    "dildo",
    "fistfuck",
    "fistfucker",
    "gook",
    "homo",
    "kike",
    "mofo",
    "muthafucka",
    "nipple",
    "pimp",
    "queer",
    "retard",
    "skank",
    "spic",
    "tits",
    "trollop",
    "wop",
    "bimbo",
    "cuntface",
    "douche",
    "fag",
    "faggy",
    "fucktard",
    "fuk",
    "jackass",
    "pussyface",
    "shithead",
    "slag",
    "smegma",
    "tosser",
    "twatface",
    "wank",
    "wanker",
    "whore"
];